DEBUG 2021-09-24 16:05:57.456 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-24 16:05:57.457 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-24 16:05:57.457 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-24 16:05:57.466 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/ssaumya/.crab3
INFO 2021-09-24 16:05:57.515 UTC: 	 Will use CRAB configuration file CRAB_cfg.py
DEBUG 2021-09-24 16:05:57.515 UTC: 	 Loading CRAB configuration file.
ERROR 2021-09-24 16:05:57.520 UTC: 	 Error while loading CRAB configuration:
name 'config' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-09-24 16:05:57.520 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'config' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-09-24 16:05:57.525 UTC: 	 Log file is /afs/cern.ch/user/s/ssaumya/Projects/CRT/CMSSW_11_3_0/src/Alignment/TrackerAlignment/test/crab.log
DEBUG 2021-09-24 16:12:31.903 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-24 16:12:31.904 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-24 16:12:31.904 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-24 16:12:31.904 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/ssaumya/.crab3
INFO 2021-09-24 16:12:31.905 UTC: 	 Will use CRAB configuration file CRAB_cfg.py
DEBUG 2021-09-24 16:12:31.905 UTC: 	 Loading CRAB configuration file.
ERROR 2021-09-24 16:12:32.276 UTC: 	 Invalid CRAB configuration: Parameter Data.totalunits is not known.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-09-24 16:12:32.276 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.totalunits is not known.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-09-24 16:12:32.296 UTC: 	 Log file is /afs/cern.ch/user/s/ssaumya/Projects/CRT/CMSSW_11_3_0/src/Alignment/TrackerAlignment/test/crab.log
DEBUG 2021-09-24 18:17:46.161 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-24 18:17:46.162 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-24 18:17:46.162 UTC: 	 Executing command: 'getlog'
DEBUG 2021-09-24 18:17:46.162 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/ssaumya/.crab3
DEBUG 2021-09-27 07:22:44.006 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-27 07:22:44.006 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.41.1.el7.x86_64 #1 SMP Tue Aug 31 14:52:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-27 07:22:44.006 UTC: 	 Executing command: 'status'
DEBUG 2021-09-27 07:22:44.007 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/ssaumya/.crab3
ERROR 2021-09-27 07:22:44.034 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/s/ssaumya/Projects/CRT/CMSSW_11_3_0/src/Alignment/TrackerAlignment/test/CRAB_CRUZET_ReReco_Monday
ERROR 2021-09-27 07:22:44.035 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/s/ssaumya/Projects/CRT/CMSSW_11_3_0/src/Alignment/TrackerAlignment/test/CRAB_CRUZET_ReReco_Monday
INFO 2021-09-27 07:22:44.059 UTC: 	 Log file is /afs/cern.ch/user/s/ssaumya/Projects/CRT/CMSSW_11_3_0/src/Alignment/TrackerAlignment/test/crab.log
